name: Build and Deploy
on:
  push:
    branches:
      - next
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@v2.0.1
        with:
         version: 7.0.0
      - name: Install and Build
        uses: actions/setup-node@v1
        with:
         cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run export
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
      - run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
